#.travis.yml
language: java

jdk:
- oraclejdk8
- openjdk7


install:
- mvn clean install -DskipTests -B -V
- mvn test cobertura:cobertura coveralls:report

#script:
#- sh ./tools/check_format.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
